### ISSUE TITLE
IE10 not loading wysiwyg view

### ISSUE THREAD

**Issue by aharris** [psergus/ngWYSIWYG#57]
I am getting a type error in IE10:
```

TypeError: Unable to get property 'addEventListener' of undefined or null reference
   at setup (http://10.0.2.2:3100/assets/js/vendor-body.js:53884:5383)
   at l (http://10.0.2.2:3100/assets/js/vendor-body.js:53884:16476)
   at Anonymous function (http://10.0.2.2:3100/assets/js/vendor-body.js:18667:34)
   at invokeLinkFn (http://10.0.2.2:3100/assets/js/vendor-body.js:18673:9)
   at nodeLinkFn (http://10.0.2.2:3100/assets/js/vendor-body.js:18167:11)
   at compositeLinkFn (http://10.0.2.2:3100/assets/js/vendor-body.js:17563:13)
   at nodeLinkFn (http://10.0.2.2:3100/assets/js/vendor-body.js:18162:24)
   at compositeLinkFn (http://10.0.2.2:3100/assets/js/vendor-body.js:17563:13)
   at compositeLinkFn (http://10.0.2.2:3100/assets/js/vendor-body.js:17566:13)

```

In chrome from the minified code
```
c.querySelector("body") === <body contenteditable="true"></body>
```

In IE:

`c.querySelector("body") === undefined`

My setup:

`<wysiwyg-edit content="text" config="editorConfig"></wysiwyg-edit>`

```
$scope.editorConfig = {
    sanitize: false,
    toolbar: [
        { name: 'basicStyling', items: ['bold', 'italic', 'underline', 'strikethrough', 'subscript', 'superscript', '-', 'leftAlign', 'centerAlign', 'rightAlign', 'blockJustify', '-'] },
        { name: 'paragraph', items: ['orderedList', 'unorderedList', 'outdent', 'indent', '-'] },
        { name: 'doers', items: ['removeFormatting', 'undo', 'redo', '-'] },
        { name: 'colors', items: ['fontColor', 'backgroundColor', '-'] },
        { name: 'links', items: ['image', 'link', 'unlink', '-'] },
        { name: 'styling', items: ['format'] }
    ]
};
```

**Comment by mecapetr** [comment]
Have you found any solution ? I have the same problem and I don´t fix it yet.

**Comment by ishthiaque** [comment]
i too am facing same issue

**Comment by vodun** [comment]
same bug!! add description that it works only Microsoft Edge!!!
