### ISSUE TITLE
TypeError: Cannot read property 'open' of null

### ISSUE THREAD

**Issue by moronboy** [psergus/ngWYSIWYG#63]
Hi There!

when i use ngWYSIWYG normal is ok
but when i use ngDialog to open a page
the ngWYSIWYG is error

`angular.js:9383 TypeError: Cannot read property 'open' of null
    at l (http://127.0.0.1:8080/assets/lib/ngWYSIWYG/dist/wysiwyg.min.js:1:16351)
    at http://127.0.0.1:8080/assets/lib/Angular/angular.js:6590:44
    at nodeLinkFn (http://127.0.0.1:8080/assets/lib/Angular/angular.js:6212:13)
    at compositeLinkFn (http://127.0.0.1:8080/assets/lib/Angular/angular.js:5622:15)
    at nodeLinkFn (http://127.0.0.1:8080/assets/lib/Angular/angular.js:6206:24)
    at compositeLinkFn (http://127.0.0.1:8080/assets/lib/Angular/angular.js:5622:15)
    at compositeLinkFn (http://127.0.0.1:8080/assets/lib/Angular/angular.js:5625:13)
    at publicLinkFn (http://127.0.0.1:8080/assets/lib/Angular/angular.js:5527:30)
    at s (http://127.0.0.1:8080/assets/lib/ngWYSIWYG/dist/wysiwyg.min.js:1:13143)
    at http://127.0.0.1:8080/assets/lib/Angular/angular.js:6590:44 <iframe style="-webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; width: 100%; height: 100%;" ng-hide="editMode" ngp-content-frame="{sanitize: config.sanitize}" content-style="" ng-model="content" class="ng-isolate-scope ng-pristine ng-valid">`

**Comment by jccv86** [comment]
I have the same Issue, with ngDialog, please fix it!

**Comment by udayRedI** [comment]
Make sure that the directive loads in the end. You can do this by setting a variable to true and using that with `ng-if` for that directive.

**Comment by albertosubero** [comment]
Thanks @udayRedI , nice solution.

**Comment by kdbusiness90** [comment]
@udayRedI, I am getting same issue but ng-if is not working for below code.

```
$.fancybox.open({
    content: template,
    type: 'html', 'transitionIn': 'elastic', 'transitionOut': 'elastic',
    afterClose : function () {
        $scope.vm.add_row = false;
        $scope.vm.edit_row = false;
        $scope.$apply();
    }
});
```
It is working fine if I removed afterClose function with ng-if.

```
$.fancybox.open({
    content: template,
    type: 'html', 'transitionIn': 'elastic', 'transitionOut': 'elastic',
});
```
